services:

  app:
    image: phucitdev/demo:latest
    container_name: demo-app
    restart: unless-stopped

    environment:
      DB_URL: jdbc:mysql://mysql:3306/githubactions-learning
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    depends_on:
      - mysql

    ports:
      - "127.0.0.1:8080:8080"

  mysql:
    image: mysql:8.4
    container_name: demo-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: githubactions-learning

    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "127.0.0.1:3306:3306"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  mysql_data:
  npm_data:
  npm_letsencrypt: